[build]
  # Сборка клиентской части
  command = "cd client && npm install && npm run build"
  # Директория сборки клиентской части
  publish = "client/dist"

[[functions]]
  name = "server"
  path = "server/main.py"
  runtime = "python3.8"
